library(dplyr)
##Question 1 : the funcion parameter is the path to the UCI HAR Dataset directory
##exemple call : test1<-question1("D:/Profiles/user/Documents/RStudio/UCI HAR Dataset")

question1<-function(directory){
      ##Load X_Train file and add 2 variables : class & id
      file1<-file.path(directory,"train/X_train.txt")
      train_data<-read.table(file=file1,header=FALSE)
      train_data%>%mutate(id=rownames(train_data),class="train")->train_data
      ##Load subject_train file,add variable id and merge with train_data
      file1a<-file.path(directory,"train/subject_train.txt")
      trainsub_data<-read.table(file=file1a,header=FALSE)
      trainsub_data%>%mutate(id=rownames(trainsub_data),subject=V1)%>%select(-c(V1))->trainsub_data
      train_data<-merge(train_data,trainsub_data,by.x="id",by.y="id")
      
      ##Load X_Test file
      file2<-file.path(directory,"test/X_test.txt")
      test_data<-read.table(file=file2,header=FALSE)
      test_data%>%mutate(id=rownames(test_data),class="test")->test_data
      
      ##Load subject_train file,add variable id and merge with test_data
      file2a<-file.path(directory,"test/subject_test.txt")
      testsub_data<-read.table(file=file2a,header=FALSE)
      testsub_data%>%mutate(id=rownames(testsub_data),subject=V1)%>%select(-c(V1))->testsub_data
      test_data<-merge(test_data,testsub_data,by.x="id",by.y="id")
      
      bind_data<-rbind(train_data,test_data)
      bind_data
}


##Question2: the funcion parameter is the path to the UCI HAR Dataset directory
## and the dataframe generated in question 1
##exemple call : test2<-question2("D:/Profiles/user/Documents/RStudio/UCI HAR Dataset",test1)
question2<-function(directory,bind_data){
      ##Load feature file and create a data frame on variables, functions and axes
      file1<-file.path(directory,"features.txt")
      feature_data<-read.table(file=file1,header=FALSE)
      temp<-strsplit(as.character(feature_data$V2),"-")
      lg<-length(temp)
      vari<-character(length=lg+3)
      ##Search the feature.txt rows for the variable name
      ## Variable name is going to be on most cases a variable name
      ## plus the function name used for the measure
      ##plus the axes 
      ## you'll notice I used a number at the end of the variable to avoid
      ##duplicated variable names
      for(i in 1:lg){
            test<-length(temp[[i]])
            if (test==1)  {
                  var<-""
                  func<-temp[[i]][1]
                  ax<-""
                  varname<-paste(func,"_",i)
            }
            if (test==2)  {
                  var<-temp[[i]][1]
                  func<-temp[[i]][2]
                  ax<-""
                  varname<-paste(var,func,"_",i)
            }
            if (test==3)  {
                  var<-temp[[i]][1]
                  func<-temp[[i]][2]
                  ax<-temp[[i]][3]
                  varname<-paste(var,func,ax,"_",i)
            }
            vari[i+1]<-varname
            
      }
      vari[1]<-"id"
      vari[564]<-"subject"
      vari[563]<-"class"
      names(bind_data)<-vari
      ##This is where we get rid of the variable not about mean or std
      bind_data%>%select(id,class,subject,matches("mean\\(\\)|std\\(\\)"))->bind_data
      bind_data
}

##Question 3 the funcion parameter is the path to the UCI HAR Dataset directory
## and the dataset generated by question 2
##exemple call : test3<-question3("D:/Profiles/user/Documents/RStudio/UCI HAR Dataset",test2)
##Load activity code for each class
question3<-function(directory,bind_data){
      file1<-file.path(directory,"test/y_test.txt")
      test_activity_code<-read.table(file=file1,header=FALSE)
      file2<-file.path(directory,"train/y_train.txt")
      train_activity_code<-read.table(file=file2,header=FALSE)
      
      ##Load activity label and merge with class data
      file3<-file.path(directory,"activity_labels.txt")
      activity_label<-read.table(file=file3,header=FALSE)
      ##merge activity code and label
      test_activity<-merge(test_activity_code,activity_label)
      test_activity%>%mutate(class="test",id=rownames(test_activity),activity=V2)%>%select(id,class,activity)->test_activity
      
      train_activity<-merge(train_activity_code,activity_label)
      train_activity%>%mutate(class="train",id=rownames(train_activity),activity=V2)%>%select(id,class,activity)->train_activity
      
      activity<-rbind(train_activity,test_activity)
      merge(bind_data,activity,all=TRUE)->bind_data
      bind_data
}
##Question 4 : the function parameter is the dataframe generated 
## in question 3
##exemple call : test4<-question4(test3)
question4<-function(bind_data){
##  variable names are already descriptive,
##only need to remove the integer at the end of variable names
      lg2<-length(names(bind_data))
      future_name<-character(lg2)
      for(i in 1:lg2){
            future_name[i]<-strsplit(names(bind_data)[i],"_")[[1]][1]
            }
      names(bind_data)<-future_name
      bind_data
}
##Question 5 : the function parameter is the dataframe generated 
## in question 4
##exemple call : test5<-question5(test4)
question5<-function(bind_data){
      bind_data%>%select(-c(id,class))%>%group_by(activity,subject)%>%summarize_all(.funs = mean)->summarised_data
      summarised_data
}

##This function is here so you don't have to chain the function call
## to get the tidy data set result. 
## exemple call 
##res<-solve_all("D:/Profiles/user/Documents/RStudio/UCI HAR Dataset")
solve_all<-function(directory){
      res1<-question1(directory)
      res2<-question2(directory,res1)
      res3<-question3(directory,res2)
      res4<-question4(res3)
      res5<-question5(res4)
      write.table(res5,file="tidydata.txt", row.names = FALSE)
      res5
}                   
